#!/usr/bin/env bash
# Installing nginx

sudo apt-get update -y
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo service nginx start
