#!/usr/bin/env bash
# Installing nginx

sudo apt-get update -y
sudo apt-get install -y nginx
echo 'Holberton School' > /var/www/html/index.html
sed -i "/server_name _/a \        rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n" /etc/nginx/sites-available/default
sudo service nginx restart
