#!/usr/bin/env bash
#printing holberton school with a condition

i=0

while [ $i -le 10 ]; do
    if [ $i = 9 ]
    then
        echo "Hi"
    else
        echo "Holberton School"
    fi
    let i+=1
done
