#!/usr/bin/env bash
#prints holbeton school but with 

i=1

while [ $i -le 10 ]; do
    if [ $i = 4 ]
    then
        echo "bad luck"
    elif [ $i = 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    let i+=1
done
