#!/usr/bin/env bash
#aAaAaAaAa

HOURS=0

while [ $HOURS -le 12 ]; do
    echo "Hour: $HOURS"
    MINUTES=1

    while [ $MINUTES -lt 60 ]; do
        echo $MINUTES
	let MINUTES+=1
    done
    
    let HOURS+=1
done
