#!/usr/bin/env bash
# configures an Ubuntu server with specific requirements

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ /etc/hosts
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
