#!/usr/bin/env bash
# Making Nginx use the nginx user
chmod 744 /etc/nginx/nginx.conf
sed -i "1iuser nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
service nginx restart
su -c "service nginx restart" nginx
